apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdn-proxy
  template:
    metadata:
      labels:
        app: cdn-proxy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: cache-volume
          mountPath: /var/cache/nginx
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: cache-volume
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=cdn_cache:10m max_size=100m inactive=60m;
    
    server {
      listen 80;
      
      location / {
        proxy_pass http://frontend.default.svc.cluster.local:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # CDN caching simulation
        proxy_cache cdn_cache;
        proxy_cache_valid 200 302 10m;
        proxy_cache_valid 404 1m;
        add_header X-Cache-Status $upstream_cache_status;
      }
      
      # Cache static assets more aggressively
      location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
        proxy_pass http://frontend.default.svc.cluster.local:80;
        proxy_cache cdn_cache;
        proxy_cache_valid 200 302 60m;
        add_header X-Cache-Status $upstream_cache_status;
        expires 1h;
      }

      location /stub_status {
        stub_status;
        allow 127.0.0.1;
        allow 10.0.0.0/8;
        allow 172.16.0.0/12;
        allow 192.168.0.0/16;
        deny all;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: cdn-proxy
spec:
  selector:
    app: cdn-proxy
  ports:
  - port: 80
    targetPort: 80
  type: NodePort